CREATE TABLE [dbo].[DIM_ORGANIZACIONAL]
(
	[COD_FILHO] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DESC_FILHO] NVARCHAR(200) NULL, 
    [COD_PAI] NVARCHAR(50) NULL, 
    [ESQUERDA] INT NULL, 
    [DIREITA] INT NULL, 
    [NIVEL] INT NULL, 
    CONSTRAINT [FK_DIM_ORGANIZACIONAL_DIM_ORGANIZACIONAL] FOREIGN KEY ([COD_PAI]) REFERENCES [DIM_ORGANIZACIONAL]([COD_FILHO])
)
