CREATE TABLE [dbo].[DIM_MARCA]
(
	[COD_MARCA] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DESC_MARCA] NVARCHAR(200) NULL, 
    [COD_CATEGORIA] NVARCHAR(50) NULL, 
    CONSTRAINT [FK_DIM_MARCA_DIM_CATEGORIA] FOREIGN KEY ([COD_CATEGORIA]) REFERENCES [DIM_CATEGORIA]([COD_CATEGORIA])
)
