CREATE TABLE [dbo].[DIM_TEMPO]
(
	[COD_DIA] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DATA] DATE NULL, 
    [COD_SEMANA] INT NULL, 
    [DIA_SEMANA] NVARCHAR(50) NULL, 
    [COD_MES] INT NULL, 
    [DESC_MES] NVARCHAR(50) NULL, 
    [COD_MES_ANO] NVARCHAR(50) NULL, 
    [DESC_MES_ANO] NVARCHAR(50) NULL, 
    [COD_TRIMESTRE] INT NULL, 
    [DESC_TRIMESTRE] NVARCHAR(50) NULL, 
    [COD_TRIMESTRE_ANO] INT NULL, 
    [DESC_TRIMESTRE_ANO] NVARCHAR(50) NULL, 
    [COD_SEMESTRE_ANO] INT NULL, 
    [DESC_SEMESTRE_ANO] NVARCHAR(50) NULL, 
    [COD_SEMESTRE] INT NULL, 
    [DESC_SEMESTRE] NVARCHAR(50) NULL, 
    [ANO] NVARCHAR(50) NULL, 
    [DIA_UTIL] NVARCHAR(50) NULL
)
