CREATE TABLE [dbo].[DIM_PRODUTO]
(
	[COD_PRODUTO] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DESC_PRODUTO] NVARCHAR(200) NULL, 
    [ATR_TAMANHO] NVARCHAR(200) NULL, 
    [ATR_SABOR] NVARCHAR(200) NULL, 
    [COD_MARCA] NVARCHAR(50) NULL, 
    CONSTRAINT [FK_DIM_PRODUTO_DIM_MARCA] FOREIGN KEY ([COD_MARCA]) REFERENCES [DIM_MARCA]([COD_MARCA])
)
