CREATE TABLE [dbo].[FATO_005]
( 
    [COD_PRODUTO] NVARCHAR(50) NOT NULL, 
    [COD_FABRICA] NVARCHAR(50) NOT NULL, 
    [COD_DIA] NVARCHAR(50) NOT NULL, 
    [META_CUSTO] FLOAT NULL, 
    PRIMARY KEY ([COD_DIA], [COD_FABRICA], [COD_PRODUTO]), 
    CONSTRAINT [FK_FATO_005_DIM_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [DIM_PRODUTO]([COD_PRODUTO]), 
    CONSTRAINT [FK_FATO_005_DIM_FABRICA] FOREIGN KEY ([COD_FABRICA]) REFERENCES [DIM_FABRICA]([COD_FABRICA]), 
    CONSTRAINT [FK_FATO_005_DIM_TEMPO] FOREIGN KEY ([COD_DIA]) REFERENCES [DIM_TEMPO]([COD_DIA])
)
