CREATE TABLE [dbo].[FATO_001]
(
	[COD_CLIENTE] NVARCHAR(50) NOT NULL , 
    [COD_PRODUTO] NVARCHAR(50) NOT NULL, 
    [COD_ORGANIZACIONAL] NVARCHAR(50) NOT NULL, 
    [COD_FABRICA] NVARCHAR(50) NOT NULL, 
    [COD_DIA] NVARCHAR(50) NOT NULL, 
    [FATURAMENTO] FLOAT NULL, 
    [IMPOSTO] FLOAT NULL, 
    [CUSTO_VARIAVEL] FLOAT NULL, 
    [QTD_VENDIDA] FLOAT NULL, 
    [UNID_VENDIDA] FLOAT NULL, 
    PRIMARY KEY ([COD_DIA], [COD_FABRICA], [COD_ORGANIZACIONAL], [COD_PRODUTO], [COD_CLIENTE]), 
    CONSTRAINT [FK_FATO_001_DIM_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES [DIM_CLIENTE]([COD_CLIENTE]), 
    CONSTRAINT [FK_FATO_001_DIM_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [DIM_PRODUTO]([COD_PRODUTO]), 
    CONSTRAINT [FK_FATO_001_DIM_ORGANIZACIONAL] FOREIGN KEY ([COD_ORGANIZACIONAL]) REFERENCES [DIM_ORGANIZACIONAL]([COD_FILHO]), 
    CONSTRAINT [FK_FATO_001_DIM_FABRICA] FOREIGN KEY ([COD_FABRICA]) REFERENCES [DIM_FABRICA]([COD_FABRICA]), 
    CONSTRAINT [FK_FATO_001_DIM_TEMPO] FOREIGN KEY ([COD_DIA]) REFERENCES [DIM_TEMPO]([COD_DIA])
)
