CREATE TABLE [dbo].[FATO_002]
(
	[COD_CLIENTE] NVARCHAR(50) NOT NULL , 
    [COD_PRODUTO] NVARCHAR(50) NOT NULL,  
    [COD_FABRICA] NVARCHAR(50) NOT NULL, 
    [COD_DIA] NVARCHAR(50) NOT NULL, 
    [FRETE] FLOAT NULL, 
    PRIMARY KEY ([COD_DIA], [COD_FABRICA], [COD_PRODUTO], [COD_CLIENTE]), 
    CONSTRAINT [FK_FATO_002_DIM_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES [DIM_CLIENTE]([COD_CLIENTE]), 
    CONSTRAINT [FK_FATO_002_DIM_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [DIM_PRODUTO]([COD_PRODUTO]), 
    CONSTRAINT [FK_FATO_002_DIM_FABRICA] FOREIGN KEY ([COD_FABRICA]) REFERENCES [DIM_FABRICA]([COD_FABRICA]), 
    CONSTRAINT [FK_FATO_002_DIM_TEMPO] FOREIGN KEY ([COD_DIA]) REFERENCES [DIM_TEMPO]([COD_DIA])
)
